import { MenuData } from "@/types"

export const dummyMenu: MenuData = {
  cafe: {
    id: "1",
    name: "Brew & Bean",
    slug: "brew-and-bean",
    description: "Artisan coffee & homemade pastries in the heart of the city.",
    logo: "",
  },
  categories: [
    {
      id: "cat-1",
      name: "Coffee",
      description: "Handcrafted espresso drinks",
      displayOrder: 1,
      dishes: [
        {
          id: "dish-1",
          name: "Classic Espresso",
          description: "Rich single-origin espresso shot",
          ingredients: ["Arabica beans", "Filtered water"],
          price: 3.50,
          image: "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=400&h=400&fit=crop",
          isAvailable: true,
          isFeatured: true,
        },
        {
          id: "dish-2",
          name: "Cappuccino",
          description: "Espresso with steamed milk foam",
          ingredients: ["Espresso", "Whole milk", "Cinnamon"],
          price: 4.50,
          image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=400&fit=crop",
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-3",
          name: "Iced Latte",
          description: "Chilled espresso with milk over ice",
          ingredients: ["Espresso", "Cold milk", "Ice"],
          price: 5.00,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-4",
          name: "Flat White",
          description: "Double espresso with velvety microfoam",
          ingredients: ["Double espresso", "Steamed milk"],
          price: 4.80,
          image: "https://images.unsplash.com/photo-1509048191080-052e615391ec?w=400&h=400&fit=crop",
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-13",
          name: "Caramel Macchiato with Extra Vanilla Syrup",
          ingredients: ["Espresso", "Vanilla syrup", "Caramel", "Steamed milk"],
          price: 6.00,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-14",
          name: "Mocha",
          ingredients: ["Espresso", "Chocolate sauce", "Steamed milk", "Whipped cream"],
          price: 5.50,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-15",
          name: "Affogato",
          ingredients: ["Vanilla gelato", "Double espresso shot"],
          price: 5.00,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-16",
          name: "Spanish Latte with Condensed Milk",
          ingredients: ["Espresso", "Condensed milk", "Whole milk"],
          price: 5.50,
          isAvailable: true,
          isFeatured: true,
        },
        {
          id: "dish-17",
          name: "Nitro Cold Brew with Honey & Cinnamon",
          ingredients: ["Cold brew coffee", "Nitrogen", "Honey", "Cinnamon"],
          price: 6.50,
          image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=400&fit=crop",
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-18",
          name: "Turmeric Golden Latte",
          ingredients: ["Turmeric", "Ginger", "Oat milk", "Black pepper", "Honey"],
          price: 5.50,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-19",
          name: "Matcha Espresso Fusion",
          ingredients: ["Matcha powder", "Espresso", "Oat milk", "Vanilla"],
          price: 6.00,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-20",
          name: "Iced Coconut Milk Latte",
          ingredients: ["Espresso", "Coconut milk", "Ice", "Simple syrup"],
          price: 5.50,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-21",
          name: "Hazelnut Macchiato with Dark Chocolate Shavings",
          ingredients: ["Espresso", "Hazelnut syrup", "Dark chocolate", "Steamed milk"],
          price: 6.50,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-22",
          name: "Pumpkin Spice Latte",
          ingredients: ["Espresso", "Pumpkin puree", "Pumpkin spice", "Steamed milk"],
          price: 6.00,
          isAvailable: true,
          isFeatured: false,
        },
      ],
    },
    {
      id: "cat-2",
      name: "Pastries",
      description: "Freshly baked daily",
      displayOrder: 2,
      dishes: [
        {
          id: "dish-5",
          name: "Croissant",
          description: "Buttery, flaky French croissant",
          ingredients: ["Puff pastry", "Butter", "Egg wash"],
          price: 3.00,
          image: "https://images.unsplash.com/photo-1555507036-ab1f4038026a?w=400&h=400&fit=crop",
          isAvailable: true,
          isFeatured: true,
        },
        {
          id: "dish-6",
          name: "Blueberry Muffin",
          description: "Soft muffin loaded with blueberries",
          ingredients: ["Flour", "Blueberries", "Sugar", "Butter"],
          price: 3.50,
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-7",
          name: "Cinnamon Roll",
          description: "Warm roll with cream cheese frosting",
          ingredients: ["Dough", "Cinnamon", "Sugar", "Cream cheese"],
          price: 4.50,
          isAvailable: true,
          isFeatured: false,
        },
      ],
    },
    {
      id: "cat-3",
      name: "Breakfast",
      description: "Served all day",
      displayOrder: 3,
      dishes: [
        {
          id: "dish-8",
          name: "Avocado Toast",
          description: "Sourdough with smashed avocado & cherry tomatoes",
          ingredients: ["Sourdough bread", "Avocado", "Cherry tomatoes", "Olive oil", "Flaky salt"],
          price: 8.00,
          image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=400&fit=crop",
          isAvailable: true,
          isFeatured: true,
        },
        {
          id: "dish-9",
          name: "Granola Bowl",
          description: "Greek yogurt, honey, fresh berries & granola",
          ingredients: ["Greek yogurt", "Granola", "Mixed berries", "Honey"],
          price: 7.50,
          isAvailable: true,
          isFeatured: false,
        },
      ],
    },
    {
      id: "cat-4",
      name: "Cold Drinks",
      description: "Refreshing beverages",
      displayOrder: 4,
      dishes: [
        {
          id: "dish-10",
          name: "Matcha Latte",
          description: "Premium Japanese matcha with oat milk",
          ingredients: ["Matcha powder", "Oat milk", "Vanilla syrup"],
          price: 5.50,
          image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=400&h=400&fit=crop",
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-11",
          name: "Fresh Lemonade",
          description: "House-made lemonade with mint",
          ingredients: ["Fresh lemon juice", "Sugar", "Mint", "Sparkling water"],
          price: 4.00,
          image: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=400&h=400&fit=crop",
          isAvailable: true,
          isFeatured: false,
        },
        {
          id: "dish-12",
          name: "Cold Brew",
          description: "Slow-steeped 24-hour cold brew",
          ingredients: ["Cold brew coffee", "Filtered water"],
          price: 4.50,
          isAvailable: true,
          isFeatured: false,
        },
      ],
    },
  ],
}

export const dummyCafes = [
  {
    id: "1",
    name: "Brew & Bean",
    slug: "brew-and-bean",
    description: "Artisan coffee & homemade pastries.",
  },
  {
    id: "2",
    name: "Green Garden Bistro",
    slug: "green-garden-bistro",
    description: "Farm-to-table salads, wraps & smoothies.",
  },
  {
    id: "3",
    name: "Pizza Piazza",
    slug: "pizza-piazza",
    description: "Wood-fired Neapolitan pizzas & craft beers.",
  },
]